# Generated by Django 5.0.1 on 2024-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank='True', null='True', upload_to='profile-image'),
            preserve_default='True',
        ),
    ]
