# Generated by Django 5.0.1 on 2024-03-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cellphone_numer',
            new_name='cellphone_number',
        ),
    ]
