# Generated by Django 5.0.1 on 2024-02-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
