# Generated by Django 5.0.1 on 2024-02-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=' ', max_length=250, unique=True),
        ),
    ]
