# Generated by Django 5.0.1 on 2024-04-07 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bootstrap_class_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_plurality',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_like',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
