# Generated by Django 5.0.1 on 2024-03-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes_post_likes_count_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_publish_bb7600_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_plurality',
            field=models.CharField(default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
