# Generated by Django 5.0.1 on 2024-03-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_options_post_bootstrap_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bootstrap_class_name',
            field=models.CharField(blank=True, default='fa fa-heart-o', max_length=20),
        ),
    ]
