# Generated by Django 5.0.1 on 2024-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_bootstrap_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('W', 'Withdrawn')], default='DF', max_length=2),
        ),
    ]
