# Generated by Django 5.0.1 on 2024-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bootstrap_class_name',
            field=models.CharField(blank=True, default='fa fa-heart-o', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_plurality',
            field=models.CharField(default='like', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
